### ISSUE TITLE
Problem with nearest location for some postcodes

### ISSUE THREAD

**Issue by peter00155** [firstred/postnl-api-php#16]
Hi,

When i want to get nearestLocation(using method getNearestLocation) for NL, for some postcodes like 3362gg, 3362aa I get warning: 
Invalid argument supplied for foreach() in file firstred\postnl-api-php\src\Service\LocationService.php
line 454 (method processGetNearestLocationsResponseREST, foreach ($location['OpeningHours'] as $day => $hour))

Could you fix it?

**Comment by firstred** [comment]
It turns out the library wasn't able to parse all the different formats coming from the REST API.

I have added all of them to the tests and it seems to pass now. They are all being normalized to the following (JSON) format:
```json
{
  "Monday": ["09:00-12:00", "13:00-16:00"],
  "Tuesday": ["09:00-12:00", "13:00-16:00"],
  "Wednesday": ["09:00-12:00", "13:00-16:00"],
  "Thursday": ["09:00-12:00", "13:00-16:00"],
  "Friday": ["09:00-12:00", "13:00-16:00"],
  "Saturday": ["09:00-14:00"],
  "Sunday": []
}
```

~~As soon as the (`$defaultProperties`) metadata has been stripped (v1.2.0), you can iterate over the opening hours as follows:~~
`Iterator` and `ArrayAccess` have been implemented, you can now simply use:
```php
foreach ($location->getOpeningHours() as $day => $timeframes) {
    if (empty($timeframes)) {} // closed
    else {
        foreach ($timeframes as $timeframe) {
            // $day       => 'Monday'
            // $timeframe => '09:00-12:00'
        }
    }
}

**Comment by firstred** [comment]
The above-mentioned solution automatically sorts from `Monday`-`Sunday`. Weeks start on Monday.
