### ISSUE TITLE
Preferred way to get status updates

### ISSUE THREAD

**Issue by GetMagented** [firstred/postnl-api-php#19]
Could anyone inform me about the preferred way to get status updates of shipments? It would be nice to have a webhook service to be notified by PostNL of any status changes  in shipments but so far I haven't found it.

In the API documentation I do see the "[updatedshipments](https://developer.postnl.nl/browse-apis/send-and-track/shippingstatus-webservice/documentation/)" method which seems to be useful to get updates of shipments. Has anybody any experience with this method? It doesn't say what an updated  shpiment is. Is it updated since the last API-call, or is it updated in last 24 hours, or ...?

Our  goal is to send a notification to  our customer when a shipment has a changed status. It seems a bit overkill to do a status-request for all your open shipments every  x minutes.
If anyone has any suggestions it would be highly appreciated.

**Comment by TomKriek** [comment]
It feels like this is not a good question for a package that just implements the API. The way you design your application is not really relevant to the package in my opinion. 
You are better off contacting PostNL on what the best options are for your application.

**Comment by firstred** [comment]
Did you ever get an answer? I believe it batches all updates since the last API call, but haven't tested it thoroughly, yet.

The solution I currently have in place is to just call the current status endpoint for every shipment that is not delivered, yet, and created < 30 days ago (international shipping partners might not always return the final shipping status). The cron job runs every hour.
