### ISSUE TITLE
Field "StreetHouseNrExt" missing in Address entity

### ISSUE THREAD

**Issue by timmtim** [firstred/postnl-api-php#5]
Was it done with purpose to not add the "StreetHouseNrExt" field in the Address entity?

**Comment by firstred** [comment]
Hi @timmtim 

Thanks for opening this issue!

There were plans to add this field, but as far as I am aware there were a couple of remarks:
> The element StreetHouseNrExt is a combination of Street, HouseNr and HouseNrExt. This field has a dependency with the field Street. One of both fields must be filled mandatory; using both fields is also allowed. This field can be used in case the values of Street, HouseNr and HouseNrExt can’t be mapped separately before calling the webservice.
> 
> This webservice will calculate a split of street name, house number and extension for you, and will afterwards use the split values. This might result in incorrect behavior for which PostNL can’t be held liable. Content in this field must be in the described order or otherwise the conversion will not work and place all values in the Street field. The conversion is only made for NL, BE and DE addresses.

In my own implementations I have been avoiding this field due to the restrictions. By using this RegEx and validating the fields manually I was able to split the string properly: https://github.com/myparcelnl/prestashop/blob/master/myparcel.php#L122

We could also add this functionality to the library itself, making exports to NL, BE and DE even easier. By converting this field to separate Street + HouseNr + Ext fields, right before serializing, we do no longer have to use this "unreliable" combination field when communicating with the PostNL API. What do you think? Would this be a good alternative?

**Comment by timmtim** [comment]
Thanks for your reply.

I don't think it is a good idea to include that regex in this library. The Netherlands has some tricky exceptions that will cause incorrect results with the provided regex. Correctly splitting the street, house number and extension from a combined string is a complex proces and there are no standard algorithms that can solve that problem for you. That is also the reason that PostNL only has that service available for NL, BE and DE. They propably have a database that they maintain with all the exceptions that the default algorithm can't handle.

I think it is best to just implement the business rules of PostNL. That means throwing an exception if the combined field is populated for unsupported countries.

**Comment by firstred** [comment]
It indeed has some tricky exceptions. I have been working with a RegEx for a while in production and am now checking how that worked out.

It looks like we can:
- safely apply the RegEx to Dutch addresses
- but not to Belgium addresses, since they might contain a box number, etc. etc. as well
- and German address are just tricky I think

So it might indeed be a better idea to try to get rid of the combined field for these countries. How about triggering a warning when the combined field is used for either NL, DE or BE? This would give developers plenty of time to start using the right fields.

Meanwhile, I'll try to merge your pull request. Totally missed it, sorry about that!

**Comment by firstred** [comment]
This pull request has been merged and the new field will land in the new version 1.2.0.
